coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
      app:
        informational: true
        paths:
          - src/
      tests:
        informational: true
        paths:
          - tests/
    patch:
      default:
        target: 75%
        threshold: 2%
      app:
        informational: true
        paths:
          - src/
      tests:
        informational: true
        paths:
          - tests/
github_checks:
  annotations: false
